name: Github Workflow Watcher

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: go build -o github-workflow-watcher-linux

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: go build -o github-workflow-watcher.exe

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-workflow-watcher-${{ matrix.os }}
          path: |
            github-workflow-watcher-linux
            github-workflow-watcher.exe
